### ISSUE TITLE
Version v0.2.0 cannot find $ANDROID_HOME

### ISSUE THREAD

**Issue by fansilva1991** [okwasniewski/MiniSim#21]
Hello,

I have updated to version 0.2.0, and when opening it, I'm getting prompted about an error to find my $ANDROID_HOME on the path.

![Screenshot 2023-02-09 at 4 07 45 PM](https://user-images.githubusercontent.com/4633618/217913258-a75e0966-e7ad-4386-9105-79a6fcff7bb1.png)

But the path is set correctly and works fine when using version 0.1.0.

I'm using MacOS Ventura 13.2 on an M1 Pro Macbook Pro.

Thanks for the support!

**Comment by okwasniewski** [comment]
Hey @fansilva1991! 

Thanks for opening the issue, can you provide which shell are you using (bash/zsh)? 

Please also provide output of command `echo $ANDROID_HOME`

And depending on your shell, make sure that following lines are in your` ~/.zprofile` or `~/.zshrc` (if you are using bash, then `~/.bash_profile` or `~/.bashrc`) config file:

```bash
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools 
```

Then click Clear cache in Preferences and restart MiniSim.

**Comment by hansemannn** [comment]
+1, was working great before!

**Comment by okwasniewski** [comment]
@hansemannn Thanks for confirming 👍 

I agree that it might be a bit harder for newbies but new solution is a lot more flexible. Previously someone with a custom setup (different location of Android Studio) wouldn't be able to use the app. 

I will add info about the PATH to README.

**Comment by fansilva1991** [comment]
@okwasniewski, my path is set correctly

```
❯ echo $ANDROID_HOME
/Users/felipenunes/Library/Android/sdk
```

But even with it, it still displays the error message. Would you happen to have any tips about how I can try to troubleshoot it? 

Again, thanks for all the support

**Comment by okwasniewski** [comment]
@fansilva1991 

Can you make sure that the ANDROID_HOME is exported from one of these files: ` ~/.zprofile` or `~/.zshrc` (if you are using bash, then `~/.bash_profile` or `~/.bashrc`). Since you may have it exported from somewhere else and that's why you have it in path in your terminal but MiniSim doesn't see it. 

Also please run `echo $SHELL` to figure out which shell you are using. 

Im following React Native docs and their export naming to make it more seamless, you can check it [here](https://reactnative.dev/docs/next/environment-setup#installing-dependencies).

**Comment by migueldaipre** [comment]
@okwasniewski +1, follow my configs.

![image](https://user-images.githubusercontent.com/21174859/218081430-53c1e38f-6b77-4b67-a5a0-575a714e530d.png)
![image](https://user-images.githubusercontent.com/21174859/218081606-409bd039-4c24-4eb0-97d4-bf6cd1b70517.png)

I cleared the cache, restarted the Mini Sim and my mac.
Thanks for the support!

**Comment by okwasniewski** [comment]
Hey @migueldaipre, @fansilva1991 

I've released new version (v0.2.1) that should solve those issues, here is the link: https://github.com/okwasniewski/MiniSim/releases/tag/v0.2.1

Let me know if this fixed your issues 🤞

**Comment by migueldaipre** [comment]
Hey @okwasniewski Its works fine.

**Comment by okwasniewski** [comment]
Thanks! Closing this

**Comment by fansilva1991** [comment]
@okwasniewski it works! Thanks.

**Comment by oertels** [comment]
Hi, the problem persists on my machine (macOS 13.1):


```
> echo $ANDROID_HOME
/Users/so/Library/Android/sdk

> ll /Users/so/Library/Android/sdk
total 8
drwxr-xr-x  18 so  staff   576B 16 Dez  2022 .
drwxr-xr-x   3 so  staff    96B  6 Jan  2020 ..
drwxr-xr-x   2 so  staff    64B  7 Jan  2022 .downloadIntermediates
-rw-r--r--@  1 so  staff    16B 19 Jun 13:45 .knownPackages
drwxr-xr-x   2 so  staff    64B 19 Jun 13:39 .temp
drwxr-xr-x  11 so  staff   352B 19 Jun 13:39 build-tools
drwxr-xr-x   4 so  staff   128B 30 Mär 10:19 cmake
drwxr-xr-x  20 so  staff   640B  7 Jan  2022 emulator
drwxr-xr-x   3 so  staff    96B  6 Jan  2020 extras
drwxr-xr-x   4 so  staff   128B 26 Mär  2021 licenses
drwxr-xr-x   4 so  staff   128B 30 Mär 10:19 ndk
drwxr-xr-x   3 so  staff    96B  6 Jan  2020 patcher
drwxr-xr-x  19 so  staff   608B  7 Jan  2022 platform-tools
drwxr-xr-x   7 so  staff   224B 30 Mär 10:31 platforms
drwxr-xr-x  32 so  staff   1,0K 10 Apr  2021 skins
drwxr-xr-x   3 so  staff    96B  6 Jan  2020 sources
drwxr-xr-x   4 so  staff   128B 15 Feb  2021 system-images
drwxr-xr-x  14 so  staff   448B  6 Jan  2020 tools
``` 

Any idea what could be the problem? Thank you!
